### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

### Compiling the ANN

In [11]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 107.4103
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 77.4105
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 63.6479
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 55.9435
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 48.8511
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 46.0977
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 43.1606
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 41.5667
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 39.2083
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 37.8908
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 37.3860
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 34.8718


### Predicting the results of the Test set

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[430.31 431.23]
 [461.32 460.01]
 [464.81 461.14]
 ...
 [472.03 473.26]
 [438.89 438.  ]
 [458.06 463.28]]


# R Squared Score


In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9124217876798997